"""Exercise Library V1: deterministic internal exercise catalog and queries."""

from app.models.exercise import (
    BodyPosition,
    DemandLevel,
    ExerciseDefinition,
    ExerciseEquipment,
    Laterality,
    MovementPattern,
    SuitableLocation,
)
from app.models.training_request import TrainingLevel
from app.services.workout_generator import get_supported_movement_patterns

EXERCISE_LIBRARY_VERSION = "exercise-library-v1"

_CATALOG: tuple[ExerciseDefinition, ...] = (
    ExerciseDefinition(
        id="push_up",
        display_name="Push-Up",
        movement_pattern=MovementPattern.horizontal_push,
        primary_regions=("chest", "shoulders", "triceps"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.floor,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="incline_push_up",
        display_name="Incline Push-Up",
        movement_pattern=MovementPattern.horizontal_push,
        primary_regions=("chest", "shoulders", "triceps"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner,),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="dumbbell_bench_press",
        display_name="Dumbbell Bench Press",
        movement_pattern=MovementPattern.horizontal_push,
        primary_regions=("chest", "shoulders", "triceps"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.dumbbell,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supine,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="barbell_bench_press",
        display_name="Barbell Bench Press",
        movement_pattern=MovementPattern.horizontal_push,
        primary_regions=("chest", "shoulders", "triceps"),
        secondary_regions=("upper_back",),
        equipment=(ExerciseEquipment.barbell,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supine,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="resistance_band_row",
        display_name="Resistance Band Row",
        movement_pattern=MovementPattern.horizontal_pull,
        primary_regions=("upper_back", "lats"),
        secondary_regions=("biceps", "rear_shoulders"),
        equipment=(ExerciseEquipment.resistance_band,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.seated,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="inverted_row",
        display_name="Inverted Row",
        movement_pattern=MovementPattern.horizontal_pull,
        primary_regions=("upper_back", "lats", "biceps"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="seated_cable_row",
        display_name="Seated Cable Row",
        movement_pattern=MovementPattern.horizontal_pull,
        primary_regions=("upper_back", "lats"),
        secondary_regions=("biceps", "rear_shoulders"),
        equipment=(ExerciseEquipment.cable,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.seated,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="single_arm_dumbbell_row",
        display_name="Single-Arm Dumbbell Row",
        movement_pattern=MovementPattern.horizontal_pull,
        primary_regions=("upper_back", "lats"),
        secondary_regions=("biceps", "core"),
        equipment=(ExerciseEquipment.dumbbell,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="half_kneeling_dumbbell_press",
        display_name="Half-Kneeling Dumbbell Press",
        movement_pattern=MovementPattern.vertical_push,
        primary_regions=("shoulders", "triceps"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.dumbbell,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.kneeling,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="seated_dumbbell_press",
        display_name="Seated Dumbbell Press",
        movement_pattern=MovementPattern.vertical_push,
        primary_regions=("shoulders", "triceps"),
        secondary_regions=("upper_back",),
        equipment=(ExerciseEquipment.dumbbell,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.seated,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="barbell_overhead_press",
        display_name="Barbell Overhead Press",
        movement_pattern=MovementPattern.vertical_push,
        primary_regions=("shoulders", "triceps"),
        secondary_regions=("upper_back", "core"),
        equipment=(ExerciseEquipment.barbell,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="resistance_band_pulldown",
        display_name="Resistance Band Pulldown",
        movement_pattern=MovementPattern.vertical_pull,
        primary_regions=("lats", "upper_back"),
        secondary_regions=("biceps",),
        equipment=(ExerciseEquipment.resistance_band,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.kneeling,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="lat_pulldown",
        display_name="Lat Pulldown",
        movement_pattern=MovementPattern.vertical_pull,
        primary_regions=("lats", "upper_back"),
        secondary_regions=("biceps",),
        equipment=(ExerciseEquipment.cable,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.seated,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="assisted_pull_up",
        display_name="Assisted Pull-Up",
        movement_pattern=MovementPattern.vertical_pull,
        primary_regions=("lats", "upper_back"),
        secondary_regions=("biceps", "core"),
        equipment=(ExerciseEquipment.machine,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="bodyweight_squat",
        display_name="Bodyweight Squat",
        movement_pattern=MovementPattern.squat_pattern,
        primary_regions=("quads", "glutes"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="goblet_squat",
        display_name="Goblet Squat",
        movement_pattern=MovementPattern.squat_pattern,
        primary_regions=("quads", "glutes"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.dumbbell, ExerciseEquipment.kettlebell),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="barbell_back_squat",
        display_name="Barbell Back Squat",
        movement_pattern=MovementPattern.squat_pattern,
        primary_regions=("quads", "glutes"),
        secondary_regions=("core", "adductors"),
        equipment=(ExerciseEquipment.barbell,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="hip_hinge_drill",
        display_name="Hip Hinge Drill",
        movement_pattern=MovementPattern.hinge_pattern,
        primary_regions=("posterior_chain",),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner,),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="kettlebell_deadlift",
        display_name="Kettlebell Deadlift",
        movement_pattern=MovementPattern.hinge_pattern,
        primary_regions=("hamstrings", "glutes"),
        secondary_regions=("upper_back", "core"),
        equipment=(ExerciseEquipment.kettlebell,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="romanian_deadlift",
        display_name="Romanian Deadlift",
        movement_pattern=MovementPattern.hinge_pattern,
        primary_regions=("hamstrings", "glutes"),
        secondary_regions=("upper_back", "core"),
        equipment=(ExerciseEquipment.barbell, ExerciseEquipment.dumbbell),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="split_squat",
        display_name="Split Squat",
        movement_pattern=MovementPattern.unilateral_lower,
        primary_regions=("quads", "glutes"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight, ExerciseEquipment.dumbbell),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="reverse_lunge",
        display_name="Reverse Lunge",
        movement_pattern=MovementPattern.unilateral_lower,
        primary_regions=("quads", "glutes"),
        secondary_regions=("hamstrings", "core"),
        equipment=(ExerciseEquipment.bodyweight, ExerciseEquipment.dumbbell),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="step_up",
        display_name="Step-Up",
        movement_pattern=MovementPattern.unilateral_lower,
        primary_regions=("quads", "glutes"),
        secondary_regions=("hamstrings", "calves"),
        equipment=(ExerciseEquipment.bodyweight, ExerciseEquipment.dumbbell),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="glute_bridge",
        display_name="Glute Bridge",
        movement_pattern=MovementPattern.posterior_chain,
        primary_regions=("glutes", "hamstrings"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supine,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="hip_thrust",
        display_name="Hip Thrust",
        movement_pattern=MovementPattern.posterior_chain,
        primary_regions=("glutes", "hamstrings"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.barbell, ExerciseEquipment.dumbbell),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="machine_hamstring_curl",
        display_name="Machine Hamstring Curl",
        movement_pattern=MovementPattern.posterior_chain,
        primary_regions=("hamstrings",),
        secondary_regions=("glutes",),
        equipment=(ExerciseEquipment.machine,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.prone,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="dead_bug",
        display_name="Dead Bug",
        movement_pattern=MovementPattern.core,
        primary_regions=("core",),
        secondary_regions=("hip_flexors",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supine,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="plank",
        display_name="Plank",
        movement_pattern=MovementPattern.core,
        primary_regions=("core",),
        secondary_regions=("shoulders", "glutes"),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.prone,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="side_plank",
        display_name="Side Plank",
        movement_pattern=MovementPattern.core,
        primary_regions=("core",),
        secondary_regions=("shoulders", "glutes"),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.floor,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.moderate,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="pallof_press",
        display_name="Pallof Press",
        movement_pattern=MovementPattern.core,
        primary_regions=("core",),
        secondary_regions=("shoulders", "glutes"),
        equipment=(ExerciseEquipment.cable, ExerciseEquipment.resistance_band),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="brisk_walk",
        display_name="Brisk Walk",
        movement_pattern=MovementPattern.conditioning,
        primary_regions=("cardiorespiratory",),
        secondary_regions=("lower_body",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="stationary_bike",
        display_name="Stationary Bike",
        movement_pattern=MovementPattern.conditioning,
        primary_regions=("cardiorespiratory", "lower_body"),
        secondary_regions=(),
        equipment=(ExerciseEquipment.machine,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.seated,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="rowing_ergometer",
        display_name="Rowing Ergometer",
        movement_pattern=MovementPattern.conditioning,
        primary_regions=("cardiorespiratory", "posterior_chain"),
        secondary_regions=("upper_back", "core"),
        equipment=(ExerciseEquipment.machine,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.seated,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.gym,),
    ),
    ExerciseDefinition(
        id="marching_in_place_intervals",
        display_name="Marching in Place Intervals",
        movement_pattern=MovementPattern.conditioning,
        primary_regions=("cardiorespiratory", "lower_body"),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="dynamic_mobility_flow",
        display_name="Dynamic Mobility Flow",
        movement_pattern=MovementPattern.mobility,
        primary_regions=("global_mobility",),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="low_impact_mobility_circuit",
        display_name="Low-Impact Mobility Circuit",
        movement_pattern=MovementPattern.mobility,
        primary_regions=("global_mobility",),
        secondary_regions=("cardiorespiratory",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="cat_cow",
        display_name="Cat-Cow",
        movement_pattern=MovementPattern.mobility_spine,
        primary_regions=("thoracic_spine", "lumbar_spine"),
        secondary_regions=("shoulders", "hips"),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.floor,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="open_book_rotation",
        display_name="Open Book Rotation",
        movement_pattern=MovementPattern.mobility_spine,
        primary_regions=("thoracic_spine",),
        secondary_regions=("shoulders",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.floor,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="hip_flexor_stretch",
        display_name="Hip Flexor Stretch",
        movement_pattern=MovementPattern.mobility_hips,
        primary_regions=("hips",),
        secondary_regions=("quads",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.kneeling,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="ninety_ninety_hip_switch",
        display_name="90/90 Hip Switch",
        movement_pattern=MovementPattern.mobility_hips,
        primary_regions=("hips",),
        secondary_regions=("core",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.floor,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.moderate,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="wall_slide",
        display_name="Wall Slide",
        movement_pattern=MovementPattern.mobility_shoulders,
        primary_regions=("shoulders",),
        secondary_regions=("upper_back",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="band_shoulder_mobility",
        display_name="Band Shoulder Mobility",
        movement_pattern=MovementPattern.mobility_shoulders,
        primary_regions=("shoulders",),
        secondary_regions=("upper_back",),
        equipment=(ExerciseEquipment.resistance_band,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.standing,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="ankle_rocker",
        display_name="Ankle Rocker",
        movement_pattern=MovementPattern.mobility_ankles,
        primary_regions=("ankles",),
        secondary_regions=("calves",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="calf_mobility_stretch",
        display_name="Calf Mobility Stretch",
        movement_pattern=MovementPattern.mobility_ankles,
        primary_regions=("ankles", "calves"),
        secondary_regions=(),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.unilateral,
        body_position=BodyPosition.supported,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="diaphragmatic_breathing",
        display_name="Diaphragmatic Breathing",
        movement_pattern=MovementPattern.breathing_core_control,
        primary_regions=("trunk", "breathing_control"),
        secondary_regions=("pelvic_control",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.supine,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
    ExerciseDefinition(
        id="crocodile_breathing",
        display_name="Crocodile Breathing",
        movement_pattern=MovementPattern.breathing_core_control,
        primary_regions=("trunk", "breathing_control"),
        secondary_regions=("upper_back",),
        equipment=(ExerciseEquipment.bodyweight,),
        training_levels=(TrainingLevel.beginner, TrainingLevel.intermediate, TrainingLevel.advanced),
        laterality=Laterality.bilateral,
        body_position=BodyPosition.prone,
        impact_level=DemandLevel.low,
        balance_demand=DemandLevel.low,
        coordination_demand=DemandLevel.low,
        suitable_locations=(SuitableLocation.home, SuitableLocation.gym, SuitableLocation.minimal_equipment),
    ),
)

_EXERCISES_BY_ID = {exercise.id: exercise for exercise in _CATALOG}


def _normalize_filter_value(value: object) -> str:
    return getattr(value, "value", value)


def _validate_catalog() -> None:
    if len(_CATALOG) != len(_EXERCISES_BY_ID):
        raise ValueError("exercise library contains duplicate exercise ids.")

    generator_patterns = set(get_supported_movement_patterns())
    catalog_patterns = {exercise.movement_pattern.value for exercise in _CATALOG}
    missing_patterns = generator_patterns - catalog_patterns
    if missing_patterns:
        raise ValueError(
            f"exercise library missing movement-pattern coverage for: {sorted(missing_patterns)}"
        )


def get_exercise_by_id(exercise_id: str) -> ExerciseDefinition | None:
    return _EXERCISES_BY_ID.get(exercise_id)


def list_exercises() -> list[ExerciseDefinition]:
    return list(_CATALOG)


def list_exercises_by_movement_pattern(
    movement_pattern: MovementPattern | str,
) -> list[ExerciseDefinition]:
    pattern_value = _normalize_filter_value(movement_pattern)
    return [exercise for exercise in _CATALOG if exercise.movement_pattern.value == pattern_value]


def list_exercises_by_equipment(
    equipment: ExerciseEquipment | str,
) -> list[ExerciseDefinition]:
    equipment_value = _normalize_filter_value(equipment)
    return [
        exercise
        for exercise in _CATALOG
        if equipment_value in {item.value for item in exercise.equipment}
    ]


def list_exercises_by_training_level(
    training_level: TrainingLevel | str,
) -> list[ExerciseDefinition]:
    training_level_value = _normalize_filter_value(training_level)
    return [
        exercise
        for exercise in _CATALOG
        if training_level_value in {level.value for level in exercise.training_levels}
    ]


def list_exercises_by_location(
    location: SuitableLocation | str,
) -> list[ExerciseDefinition]:
    location_value = _normalize_filter_value(location)
    return [
        exercise
        for exercise in _CATALOG
        if location_value in {item.value for item in exercise.suitable_locations}
    ]


_validate_catalog()
