"""
Input model for POST /api/v1/training/recommendation.

Follows data minimization principles: only the fields required to compute
a training recommendation are accepted. No PII, no medical data, no
detailed menstrual calendars.
"""

from enum import Enum

from pydantic import BaseModel, Field, field_validator


class Sex(str, Enum):
    male = "male"
    female = "female"


class Goal(str, Enum):
    general_fitness = "general_fitness"
    fat_loss = "fat_loss"
    muscle_gain = "muscle_gain"
    strength = "strength"
    endurance = "endurance"
    mobility = "mobility"


class TrainingLevel(str, Enum):
    beginner = "beginner"
    intermediate = "intermediate"
    advanced = "advanced"


class SessionType(str, Enum):
    upper_body = "upper_body"
    lower_body = "lower_body"
    full_body = "full_body"
    cardio = "cardio"
    mobility = "mobility"
    rest = "rest"
    unknown = "unknown"


class CyclePhase(str, Enum):
    menstruation = "menstruation"
    follicular = "follicular"
    ovulation = "ovulation"
    luteal = "luteal"
    unknown = "unknown"


class CycleDiscomfort(str, Enum):
    none = "none"
    mild = "mild"
    moderate = "moderate"
    high = "high"


class CycleContext(BaseModel):
    """Optional, minimal cycle context. Only used when relevant."""

    phase: CyclePhase
    discomfort: CycleDiscomfort = CycleDiscomfort.none


class TrainingRecommendationRequest(BaseModel):
    # Optional internal anonymous ID generated by Base44. Must NOT contain PII.
    user_id: str | None = Field(
        default=None,
        description="Anonymous internal ID generated by Base44. Must not contain PII.",
        max_length=128,
    )

    age: int = Field(..., ge=10, le=100)
    sex: Sex
    height_cm: float = Field(..., gt=0, le=300)
    weight_kg: float = Field(..., gt=0, le=400)

    goal: Goal
    training_level: TrainingLevel
    training_days_per_week: int = Field(..., ge=1, le=7)
    fatigue_level: int = Field(..., ge=1, le=5)

    last_session_type: SessionType | None = None
    hours_since_last_session: int | None = Field(default=None, ge=0)

    cycle_context: CycleContext | None = None

    @field_validator("user_id")
    @classmethod
    def reject_obvious_pii(cls, value: str | None) -> str | None:
        """Very light guardrail: reject values that look like an email."""
        if value and "@" in value:
            raise ValueError(
                "user_id must be an anonymous internal identifier, not an email."
            )
        return value
